language: node_js
node_js:
- '6'
env:
  global:
  - secure: rvHWhl5pmr0TMlnM8OJC7Lr88rdshvoBwLjUPv1uNg/zYb0Y4C7gL8t/55q7jwG5BvkKGJiJJxSi9+vPUvDDc+PiaWURM+hvw7Sz48z0GXSiquLD2/tCHxCTU/+2jLx6NLkN4pDzp07RLYzM4260VWgqneLrlqvKEXqxUClCu4SzBH6RviG7zGDEEa+OW7DoQTj8PEevIcC+9obPgSHOXN+sn4uCDdo1+5G9eFiRlCBj/vZmiT8O3+3MdtB8Q6nbX3pNLnaydZDioyiug6RlS1yw37n4LLc1mC7d2MVQE/+eO4itXlHGKFIsfplh3yV+IJz+q1kXnsby2d/YJ8MQkC+aOS4rnjZQ1hE8YJTd0Sfi4iJA38diDkcW6M6NcKPxpvK+4HCeQrd+HJO1j8jOTkjpHtiHKw/6+su89wdG2nnN29oGfJ483heSi47b+B1LFAx+hkUBykIPYz/swXq9hhwDXj+gllm3H1COJN6KmdQOWkzE/ojBqbb3RRJgnRL1E7FRg4Fcg6K+NNbFHuZAA9WQGDMuhCU0LjmziRaXlB7RF6mdr8dBYTgTC2pxZdl9hJyoDIoSTk5hKd56x9eQ0twH92x3iELWPIrjqcKJSrXV0obg4+gGC8JiKAs+ErWtanv5n7j/eiC9LY1I20yoHqyAA3Vs0dyVi/c9bUdM97c=
branches:
  only:
  - develop
  except:
  - master
script:
- yarn install
- yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
  on:
    branch: develop
  target_branch: master
